# Generated by Django 4.2.11 on 2024-04-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="form",
        ),
        migrations.AddField(
            model_name="document",
            name="pdf_path",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="lodgement",
            name="image_path",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
