# Generated by Django 4.2.11 on 2024-04-16 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_remove_document_form_document_pdf_path_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="queue",
            name="lodgement_size",
            field=models.IntegerField(choices=[(1, "1+1"), (2, "2+1")], default=1),
        ),
    ]
